### ISSUE TITLE
Verify TP Lists

### ISSUE THREAD

**Issue by rbillings** [rbillings/shavar-e2e-tests#16]
Create a FF profile with the BASE list.  For issue #11 
- Create a Firefox profile with specific prefs - block #7
- Verify file cache sizes - block #15
- Verify ItisaTrap page display - block #13 
- Verify Tracking Protection shield displays - block Foxpuppet issue https://github.com/mozilla/FoxPuppet/issues/72

**Comment by rbillings** [comment]
Updated issue title to more accurately reflect that this is to verify that we are able to fully verify each type of list, and to go through the battery of tests for each list-type profile. Lists include:
BASE
MOZFULL
MOZSTD
MOZTESTPUB
MOZSTAGING

**Comment by rpappalax** [comment]
Thank you so much, @rbillings 🙏 Yea, i think our README for these is going to read like War and Peace. If we keep good notes in the issues, we can revisit them when we update the README to reflect the final product.
