### ISSUE TITLE
Add ability to run tests in proper order

### ISSUE THREAD

**Issue by rpappalax** [rbillings/shavar-e2e-tests#28]
Tests will leave profile by-products behind that we'll need to reconsume on subsequent tests.

**Comment by rpappalax** [comment]
i believe @jrbenny35 mentioned there's a pytest plugin for this ?

**Comment by jrbenny35** [comment]
I don't quite follow. A pytest plugin to rerun tests?

**Comment by rpappalax** [comment]
@jrbenny35 if you just run "tox" isn't it the case that tests aren't necessarily guaranteed to run in any particular order?   is there a way to force a particular order?  @rbillings i believe this may be what we need:
http://pytest-ordering.readthedocs.io/en/develop/

**Comment by rpappalax** [comment]
this is a non-issue.  we now can do our setup, then test in the proper order
