### ISSUE TITLE
Fix tests to pull pref_set from fixture (not env var)

### ISSUE THREAD

**Issue by rpappalax** [rbillings/shavar-e2e-tests#40]
instead of env var:

https://github.com/rbillings/shavar-e2e-tests/blob/master/tests/test_itisatrap_page.py#L6

**Comment by rbillings** [comment]
I believe environment variables have been addressed- shall we close this issue @rpappalax ?

**Comment by rpappalax** [comment]
@rbillings thank for doing this housekeeping!  yes, but we should probably remove all the env vars from this test and elsewhere that no longer apply before we close the issue (so we don't leave them around)

**Comment by rbillings** [comment]
Env vars have been removed from all current tests, change is included in pull request #51 .

**Comment by rbillings** [comment]
Resolved in #49  & #51
