### ISSUE TITLE
Remove test_itisatrap_page

### ISSUE THREAD

**Issue by rpappalax** [rbillings/shavar-e2e-tests#59]

**Comment by rpappalax** [comment]
@rbillings are you able to get the cat and fox to work using OSX?  for me it just shows up without either:
![image](https://user-images.githubusercontent.com/3699494/39718287-b36511a0-51ea-11e8-8564-476a625d1c03.png)

**Comment by rpappalax** [comment]
@rbillings also, i noticed that testrail maybe needs updating.  it shows the test page as:  https://people.mozilla.org/~fmarier/tracking-test/  not:  https://www.itisatrap.org/firefox/its-a-trap.html

**Comment by rbillings** [comment]
1) there is no cat or fox for this test, but also no the test does not pass
2) the link is outdated
3) it seems that all of the trackers [1st party, 3rd party, DNT] have been removed from the itisatrap page itself, so the test should be removed

**Comment by rbillings** [comment]
Addressed in #65
